### ISSUE TITLE
Store Secret (from command line)

### ISSUE THREAD

**Issue by econmang** [Spooky-Action-Developers/Project-Ironclad#12]
As a Mozilla Employee, I want to securely store a secret credential from the command line through Amazon Web Services to guarantee privacy of my information.

**Comment by econmang** [comment]
Note: This user story, and others like it, will relate to the functions that need to be implemented back end to handle data requests from users. The UI and I/O commands associated with the parser of the system are marked with a 'ui' label.

**Comment by econmang** [comment]
Note: Once this issue is handled, this will verify that we have completed FE-4 and FE-5, as well.

**Comment by econmang** [comment]
Rolling this issue onto next Sprint. Was not able to complete it; though it should be noted that this is the last issue on Sprint One's backlog. This issue will be kept open, but also be broken into more granule issues.

The granule issues are #42 and #43

**Comment by Beardnoceris** [comment]
Completed by #55
