### ISSUE TITLE
Create Access Grants

### ISSUE THREAD

**Issue by Beardnoceris** [Spooky-Action-Developers/Project-Ironclad#14]
As a Mozilla Employee, I want to create access grants so that I can allow other users to access my secrets.

**Comment by Beardnoceris** [comment]
Completed by #96

**Comment by econmang** [comment]
After review, me and @Beardnoceris have decided to remove grants functionality until we have more information detailing their necessity. As such, I am marking this as 'wontfix' until a later date and removing the requires test label.
