### ISSUE TITLE
Store Secret From Stdin (Default Table)

### ISSUE THREAD

**Issue by econmang** [Spooky-Action-Developers/Project-Ironclad#23]
As a Mozilla Employee, I want to be able to store a secret from standard input using the Unix piping tool so that I can quickly redirect output for storage.

**Comment by econmang** [comment]
Moving this to Sprint Three because it relies on updated form of put secret function.

**Comment by econmang** [comment]
Realistically, I'm second-guessing this as a feature. What do you think @Beardnoceris. Personally, I added this thinking it could be useful to concat some file outputs, but, realistically, I'm thinking it should be incumbent on user to specify files, or to concat files into one before using our -f flag. Plus, CLAP doesn't seem to support piping functionality.

If you think it could be easily implemented, then we can go ahead and do it, but, if you feel the same, I move that we mark this as non-necessary and close the issue without implementing this feature.

**Comment by Beardnoceris** [comment]
For now I suggest closing this issue. If the client specifically requests this capability, we can find a work around for CLAP and piping.
