### ISSUE TITLE
Add rustfmt to travisCI

### ISSUE THREAD

**Issue by andrewkrug** [Spooky-Action-Developers/Project-Ironclad#33]
Suggestion: 

Use an inline linter both in the IDE you're writing code in as well as in your CI pipeline to make sure you're writing code that conforms to the rustfmt style guide.

https://github.com/rust-lang-nursery/rustfmt 
^^ Here's a good example of a linter you can run.  This will also help you catch errors on Pull Request.

**Comment by andrewkrug** [comment]
Here's another example of an alternative linter suggested in #rust 

clippy : https://github.com/rust-lang-nursery/rust-clippy

https://github.com/yoshuawuyts/human-panic/blob/e82d2ed28f5802959f4f78f36ae8eed863dff445/.travis.yml#L13-L19

**Comment by econmang** [comment]
That's a good suggestion, and not to hard to implement. I'll get right on it.

**Comment by econmang** [comment]
Fixed with #40
