### ISSUE TITLE
Add a project CHANGELOG

### ISSUE THREAD

**Issue by andrewkrug** [Spooky-Action-Developers/Project-Ironclad#34]
Suggestion:

Add a changelog for notifying users about what's in new tagged releases both MAJOR / MINOR versions.

https://keepachangelog.com/en/1.0.0/

You also my want to consider calling out in the README that you're using semantic versioning.

https://semver.org/

**Comment by econmang** [comment]
Thanks for the suggestion of adding the Changelog. I've open pull request #50 in the hopes of rectifying this. I did have a clarification question, though. If we are using semver and Changelog from this point onwards, how do we handle/reflect previous development cycles before implementing both of these?

In the Changelog, I have attempted to handle this by yanking the initial release and clustering the development until now into the 0.2.0 header. If this is sufficient, please feel free to close this issue and we will forge ahead utilizing the Changelog as is.
