### ISSUE TITLE
Create default_table

### ISSUE THREAD

**Issue by Beardnoceris** [Spooky-Action-Developers/Project-Ironclad#37]
As a Mozilla Employee, I want to create a default table, so that I can make a table without specifying specific values.

**Comment by econmang** [comment]
Tested create_table function from #35 and, when no arguments specified, it will create default Test_Table.

**Comment by econmang** [comment]
Updated Test Plan with new output of ```cargo run setup```, Ironclad-store, when no argument is specified.
