### ISSUE TITLE
Add Grant Function Calls to Parser

### ISSUE THREAD

**Issue by Beardnoceris** [Spooky-Action-Developers/Project-Ironclad#97]
As a Mozilla Employee, I want to use grants to give and revoke access to different secrets, so that I can share secret keys with other accounts. 

Grant function call mod has been added to project, add function calls to parser/main.rs

**Comment by econmang** [comment]
Do to the variable nature of grants and lacking a clear example of their desired/intended use, I am marking that we will not implement this feature. If we get more information or examples of its use, we may implement in a later version.
